import streamlit as st
import sys
import os
from interface.constants import RISK_PROFILE_DICTIONARY, RISK_COLOR, ASSETS_PATH, BASE_DIR

def apply_global_styles():
    """
    Computes apply global styles.

    Parameters
    ----------

    Returns
    -------
    Any: apply global styles output.
    """
    # Global CSS for the whole app: fonts, colors, buttons, cards, etc.
    # Basically to make everything look nicer and consistent
    st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');

    /* Force Roboto everywhere (Streamlit uses weird autogenerated classes) */
    html, body, [class*="css"] {
        font-family: 'Roboto', sans-serif !important;
    }

    /* Light background so it doesn't look too heavy */
    body {
        background-color: #F8FAFC;
    }

    /* Reduce top padding a bit so content starts higher */
    .main > div {
        padding-top: 1rem;
    }

    /* Button styling: colors, size, rounded corners */
    .stButton > button {
        background-color: #73EDFF;
        color: #000078;
        border-radius: 8px;
        padding: 0.6rem 1.2rem;
        font-size: 1.1rem;
        font-weight: 700;
        border: 2px solid #000078;
    }

    /* Button hover effect (kept simple on purpose) */
    .stButton > button:hover {
        background-color: #73EDFF;
    }

    /* Card-style containers used all over the app */
    .card {
        background-color: white;
        padding: 1.8rem;
        border-radius: 12px;
        box-shadow: 0 10px 25px rgba(0,0,0,0.05);
        height: 100%;
    }

    /* Sticky element that stays visible when scrolling */
    .progress-sticky {
        position: sticky;
        top: 0;
        z-index: 9999;        
        background: #F8FAFC;
        }

        /* Prevent content from being cut due to overflow */
        .stApp {
        overflow: visible;
        }

    </style>
    """, unsafe_allow_html=True)


def render_sidebar_header():
    """
    Renders sidebar header.

    Parameters
    ----------

    Returns
    -------
    Any: render sidebar header output.
    """
    # Everything inside here goes into the sidebar
    with st.sidebar:
        # University logo at the top
        st.image(str(ASSETS_PATH / "202-nova-marca-uoc.jpg"), width="stretch")

        # Sidebar title and subtitle
        st.markdown("""
        <div style="margin-top:0.6rem; margin-bottom:0.8rem; text-align:center;">
            <div style="color:#000078; font-weight:700; font-size:1.05rem;">
                ROBO-UOC ADVISOR
            </div>
            <div style="color:#000078; opacity:0.85; font-size:0.9rem;">
                TFG - UOC
            </div>
        </div>
        """, unsafe_allow_html=True)

        # Simple separator to keep things tidy
        st.markdown("---")


def render_sidebar_profile_summary():
    """
    Renders sidebar profile summary.

    Parameters
    ----------

    Returns
    -------
    Any: render sidebar profile summary output.
    """
    # If the questionnaire hasn't been completed yet, do nothing
    if "risk_result" not in st.session_state:
        return

    # Get stored risk profile results
    res = st.session_state["risk_result"]
    RT = res["RT"]

    # Color depends on the risk level
    color = RISK_COLOR[RT]

    # Separator before showing the profile info
    st.sidebar.markdown("---")

    # Display risk profile name and number in a clear visual way
    st.sidebar.markdown(
        f"""
        <div style="text-align: center">
            <div style="font-size: 18px; font-weight: 1200; color: {color}; margin-top: 6px;">
                {RISK_PROFILE_DICTIONARY[RT]}
            </div>
            <div style="font-size: 28px; font-weight: 1200; color: {color}; margin-top: 6px;">
                {RT}
            </div>
        </div>
        """,
        unsafe_allow_html=True
    )


def render_sidebar():
    """
    Renders sidebar.

    Parameters
    ----------


    Returns
    -------
    Any: render sidebar output.
    """
    # Base sidebar content (logo + title)
    render_sidebar_header()


def render_portfolio():
    """
    Renders portfolio.

    Parameters
    ----------

    Returns
    -------
    Any: render portfolio output.
    """
    # User must complete the risk questionnaire first
    if "risk_result" not in st.session_state:
        st.warning("Primero completa el cuestionario de perfil de riesgo.")
        return

    # Extract final risk profile and volatility range
    res = st.session_state["risk_result"]
    RT = res["RT"]
    sigma_min = res["sigma_min"]
    sigma_max = res["sigma_max"]

    # Section title
    st.header("Cartera de inversión recomendada")

    # Show final profile summary
    st.write(
        f"Perfil de riesgo final: **{RT} – {RISK_PROFILE_DICTIONARY[RT]}**"
    )
    st.write(
        f"Volatilidad objetivo: **{sigma_min * 100:.1f}% – {sigma_max * 100:.1f}%**"
    )

    # Placeholder for future portfolio logic and charts
    st.info("Aquí iría la construcción de la cartera (pesos por activo, gráficos, etc.).")


def header(text: str):
    """
    Computes header.

    Parameters
    ----------
    text : str. text.

    Returns
    -------
    Any: header output.
    """
    # Big centered header used as a visual section title
    st.markdown(f"""
                <div style="display:flex; justify-content:center; margin-bottom:1.5rem;">
                <div style="
                background: linear-gradient(135deg, rgba(115,237,255,0.15), rgba(115,237,255,0.05));
                border: 2px solid #000078;
                border-radius: 12px;
                padding: 0.9rem 1.6rem;
                box-shadow: 0 10px 30px rgba(115,237,255,0.15);
                text-align: center;
                ">
                <span style="
                display:block;
                color:#000078;
                font-size:3.15rem;
                font-weight:800;
                letter-spacing:0.1em;
                line-height:1.1;
                ">
                {text}
                </span>
                </div>
                </div>    
                </div>""", unsafe_allow_html=True)


def subheader(text: str, font_size: str = "1.1rem", margin_bottom: str = "-1.0rem", font_weight: str = "600",
              color: str = "#000078"):
    """
    Computes subheader.

    Parameters
    ----------
    text : str. text.
    font_size : str. font size.
    margin_bottom : str. margin bottom.
    font_weight : str. font weight.
    color : str. color.

    Returns
    -------
    Any: subheader output.
    """
    # Smaller reusable subtitle with custom size, color and spacing

    st.markdown(f"""
            <div style="
            font-size: {font_size};
            font-weight: {font_weight};
            color: {color};
            line-height: 1.6;
            margin-bottom: {margin_bottom};
            text-align: center;
            max-width: 800px;
            margin-left: auto;
            margin-right: auto;
            ">
            {text}
            </div>
          """, unsafe_allow_html=True)


sys.path.append(os.path.join(os.path.dirname(__file__), "src"))